name: kliencash
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.1.0
  calendar_date_picker2: ^2.0.1
  country_code_picker: ^3.4.1
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_slidable: ^4.0.3
  google_fonts: ^6.3.2
  image_picker: ^1.2.1
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  sqflite: ^2.4.2
  syncfusion_flutter_charts: ^28.2.6

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lang/en.json
    - assets/lang/id.json
