name: kliencash
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.1.0
  country_code_picker: ^3.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  google_fonts: ^6.3.2
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  syncfusion_flutter_charts: ^28.2.6

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
